export const ERROR_MESSAGE = {
  USER_NOT_FOUND: 'User not found.',
  EMAIL_ALREADY_EXISTED: 'Email already existed.',
  INCORRECT_USERNAME_OR_PASSWORD: 'Incorrect username or password.',
  YOU_ARE_ALREADY_A_TUTOR: 'You are already a tutor.',
  TUTOR_REQUEST_NOT_FOUND: 'Tutor request not found.',
  COURSE_NOT_FOUND: 'Course not found.',
  CAN_NOT_UPDATE_PUBLISHED_COURSE: 'Can not update published course.',
  SUBJECT_ALREADY_MAPPED_TO_GRADE: 'This subject already mapped to grade.',
  SUBJECT_NAME_IS_ALREADY_EXISTS: "Subject's name is already exists.",
  GRADE_NOT_FOUND: 'Grade not found.',
  SUBJECT_NOT_FOUND: 'Subject not found.',
  SUBJECT_MAP_GRADE_NOT_FOUND: 'Subject map grade not found.',
  TUTOR_REVIEW_NOT_FOUND: 'Subject not found.',
  CAN_NOT_DELETE_THIS_TUTOR_REQUEST: 'Can not delete this tutor request.',
  INVALID_STATUS: 'Invalid status.',
  TUTOR_DETAIL_NOT_FOUND: 'Tutor detail not found.',
  CLASS_NOT_FOUND: 'Class not found.',
  CAN_NOT_UPDATE_SCHEDULE_OF_CLASS_OF_PUBLISHED_COURSE: 'Can not update schedule of class of published course',
  CAN_NOT_DELETE_THIS_CLASS: 'Can not delete this class.',
  INVALID_SCHEDULE: 'Invalid schedule.',
  ENROLMENT_NOT_FOUND: 'Enrolment not found.',
  NAME_OF_CLASS_IS_ALREADY_EXISTED: "Class's name is already existed.",
  COURSE_IS_ALREADY_PUBLISHED: 'Course is already published.',
  COURSE_DOESNT_HAS_ANY_CLASSES: `Course doesn't has any classes.`,
  THIS_COURSE_IS_NOT_PUBLISHED: 'This course is not published.',
  ASSIGNMENT_NOT_FOUND: 'Assignment not found.',
  QUIZ_NOT_FOUND: 'Quiz not found.',
  NOT_IN_ANSWER_TIME_OF_THIS_QUIZ: 'Not in answer time of this quiz.',
  YOU_ALREADY_ENROLLED: 'You already enrolled this course.',
}
