export const ERROR_MESSAGE = {
  USER_NOT_FOUND: 'User not found.',
  EMAIL_ALREADY_EXISTED: 'Email already existed.',
  INCORRECT_USERNAME_OR_PASSWORD: 'Incorrect username or password.',
  YOU_ARE_ALREADY_A_TUTOR: 'You are already a tutor.',
  TUTOR_REQUEST_NOT_FOUND: 'Tutor request not found.',
  COURSE_NOT_FOUND: 'Course not found.',
  CAN_NOT_UPDATE_PUBLISHED_COURSE: 'Can not update published course.',
  SUBJECT_ALREADY_MAPPED_TO_GRADE: 'This subject already mapped to grade.',
  SUBJECT_NAME_IS_ALREADY_EXISTS: "Subject's name is already exists.",
  GRADE_NOT_FOUND: 'Grade not found.',
  SUBJECT_NOT_FOUND: 'Subject not found.',
  SUBJECT_MAP_GRADE_NOT_FOUND: 'Subject map grade not found.',
  TUTOR_REVIEW_NOT_FOUND: 'Subject not found.',
  CAN_NOT_DELETE_THIS_TUTOR_REQUEST: 'Can not delete this tutpr request.',
  INVALID_STATUS: 'Invalid status.',
  TUTOR_DETAIL_NOT_FOUND: 'Tutor detail not found.',
}
