export const ERROR_MESSAGE = {
  USER_NOT_FOUND: 'User not found.',
  EMAIL_ALREADY_EXISTED: 'Email already existed.',
  INCORRECT_USERNAME_OR_PASSWORD: 'Incorrect username or password.',
  YOU_ARE_ALREADY_A_TUTOR: 'You are already a tutor.',
  TUTOR_REQUEST_NOT_FOUND: 'Tutor request not found.',
  COURSE_NOT_FOUND: 'Course not found.',
  CAN_NOT_UPDATE_PUBLISHED_COURSE: 'Can not update published course.',
  SUBJECT_ALREADY_MAPPED_TO_GRADE: 'This subject already mapped to grade.',
  SUBJECT_NAME_IS_ALREADY_EXISTS: "Subject's name is already exists.",
  GRADE_NOT_FOUND: 'Grade not found.',
  SUBJECT_NOT_FOUND: 'Subject not found.',
  SUBJECT_MAP_GRADE_NOT_FOUND: 'Subject map grade not found.',
  TUTOR_REVIEW_NOT_FOUND: 'Tutor review not found.',
  CAN_NOT_DELETE_THIS_TUTOR_REQUEST: 'Can not delete this tutor request.',
  INVALID_STATUS: 'Invalid status.',
  TUTOR_DETAIL_NOT_FOUND: 'Tutor detail not found.',
  CLASS_NOT_FOUND: 'Class not found.',
  CAN_NOT_UPDATE_CLASS_OF_PUBLISHED_COURSE: 'Can not update class of published course',
  CAN_NOT_DELETE_THIS_CLASS: 'Can not delete this class of published course.',
  OVERLAPPED_SCHEDULE: 'Overlapped schedule.',
  ENROLMENT_NOT_FOUND: 'Enrolment not found.',
  NAME_OF_CLASS_IS_ALREADY_EXISTED: "Class's name is already existed.",
  COURSE_IS_ALREADY_PUBLISHED: 'Course is already published.',
  COURSE_DOESNT_HAS_ANY_CLASSES: `Course doesn't has any classes.`,
  THIS_COURSE_IS_NOT_PUBLISHED: 'This course is not published.',
  ASSIGNMENT_NOT_FOUND: 'Assignment not found.',
  QUIZ_NOT_FOUND: 'Quiz not found.',
  NOT_IN_ANSWER_TIME_OF_THIS_QUIZ: 'Not in answer time of this quiz.',
  YOU_ALREADY_ENROLLED: 'You already enrolled this course.',
  TUTOR_REPORT_NOT_FOUND: 'Tutor report not found.',
  PAYMENT_NOT_FOUND: 'Payment not found.',
  THIS_CLASS_IS_FULL: 'This class is full.',
  CLASS_IS_ALREADY_FINISHED: 'This course is already finished.',
  YOU_MUST_PUBLISH_A_COURSE_BEFORE_IT_STARTS: 'You must publish a course before it starts.',
  MISMATCH_IN_SCHEDULE_START_DAY: 'Mismatch in schedule start day.',
  MISMATCH_IN_SCHEDULE_END_DAY: 'Mismatch in schedule end day.',
  OVERDUE_FOR_PAYMENT: 'Overdue for payment.',
  YOU_HAVE_NOT_BEEN_STUDENT_OF_THIS_TUTOR_BEFORE: 'You have not been student of this tutor before.',
  START_DATE_MUST_BE_BEFORE_END_DATE: 'Start date must be before end date.',
  CLASS_NOT_STARTED: 'Class has not started at this time.',
  CANNOT_CREATE_CLASS_OF_PUBLISHED_COURSE: 'Can not create class of published course.',
  CANNOT_DELETE_PUBLISHED_COURSE: 'Can not delete published course.',
  YOU_ALREADY_REVIEW_THIS_TUTOR: 'You already review this tutor.',
  INVALID_TOTAL_MONTHS: 'The number of months is invalid.',
  INVALID_ANSWER_TIME_OF_QUIZ: `Invalid quiz's answer time.`,
  CANNOT_DELETE_SUBJECT_HAVE_PUBLISHED_COURSE: 'You can not delete a subject which has a published course.',
  CANNOT_DELETE_GRADE_HAVE_PUBLISHED_COURSE: 'You can not delete a grade which has a published course.',
}
